services:
  backend:
    build:
      context: ./Backend/tahiti-time-numerique/tahiti-time-numerique
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
  frontend:
    build:
      context: ./Frontend/Frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8080
    depends_on:
      - backend